### ISSUE TITLE
Allow to pass Proxy Configurations on TrueLayerClient initialization

### ISSUE THREAD

**Issue by tstukalova** [TrueLayer/truelayer-java#198]
**Is your feature request related to a problem? Please describe.**
There is a need to allow to pass proxy configurations while creating a TrueLayer Client. Our team can not use the functionality of the library, since we use a Proxy for all outgoing requests, so we're blocked on that. 

**Describe the solution you'd like**
We have a proxy which is set in env variable, the format is: http://$USER:$PASSWORD@$HOST:@PORT
1st possible solution is to add an ability to pass a proxy configurations during TrueLayerClient initialization.
2nd solution which is acceptable for us, but might be not for others is read proxy configurations from environment variables during OkHttpClient initialization (in your `OkHttpClientFactory` class)

**Describe alternatives you've considered**
Here is possible workaround we used to check the request goes through our http proxy. This is very specific to our case and might need to be updated.
In OkHttpClientFactory:

```
private void setHttpProxy(OkHttpClient.Builder clientBuilder) {
  String httpProxy = System.getenv("http_proxy");
  if (httpProxy == null) {
    return;
  }

  URI proxyUri = URI.create(httpProxy);
  clientBuilder.proxy(
      new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyUri.getHost(), proxyUri.getPort())));

  String userInfo = proxyUri.getUserInfo();
  if (userInfo == null) {
    return;
  }

  String[] userInfoParams = userInfo.split(":");
  String userName = userInfoParams[0];
  String password = userInfoParams[1];

  if (userName != null && password != null) {
    Authenticator proxyAuthenticator = (route, response) -> {
      String credential = Credentials.basic(userName, password);
      return response.request().newBuilder()
          .header("Proxy-Authorization", credential)
          .build();
    };
    clientBuilder.proxyAuthenticator(proxyAuthenticator);
  }
}

```
and in method `buildBaseApiClient` just call the method above.

**Additional context**

**Comment by dili91** [comment]
Thanks for raising this 👁️

**Comment by dili91** [comment]
Hey @tstukalova, I've sketched a proposal to support custom proxies with an optional set of credentials. You can check [this](https://github.com/TrueLayer/truelayer-java/commit/96d2629f6be918631b49cdd8f5e7debe24763f10) commit and let us know if that would work for you. You could even try this on the snapshot artifact `6.3.0-proxy-config-SNAPSHOT`

Differently from the suggested code above we're not using env variables but we'd like to go with an explicit configuration on our `TrueLayerClient` type, as it is more consistent with our library. 

You could configure your proxy like this: 

```
var tlClient = TrueLayerClient.New()
                ...
                .withProxyConfiguration(ProxyConfigurations.builder()
                        .hostname("127.0.0.1")
                        .port(9999)
                        .credentials(ProxyConfigurations.Credentials.builder()
                                .username("john")
                                .password("doe")
                                .build())
                        .build())
                .build();
```

Realistically we won't support proxies different from `HTTP`, therefore relying on the new `ProxyConfiguration` class seems to work for us. Let us know if that's true for your case as well 👋
